# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

install! 'cocoapods', :warn_for_unused_master_specs_repo => false

target 'DavidOcDemos' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  # warn_for_unused_master_specs_repo => false

  # Pods for DavidOcDemos

  pod 'GPUImage'

  target 'DavidOcDemosTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DavidOcDemosUITests' do
    # Pods for testing
  end

end
